### ISSUE TITLE
Map interface breaks in non-chrome webbrowsers

### ISSUE THREAD

**Issue by MisterChalmers** [chalmersproject/openshelter#6]
Something strange is happening with the Shelter Location popup styling in non-chrome browsers. 

- Large brown boxes block sections of the UI. 
- Elements on the popup in the foreground disappear when the map in background is moved.

I'm not sure what's causing these UI bugs. The popups work as expected in chromium based browsers. 

I wonder if we could solve this issue using a css-postprocessor to add a bunch of compatibility gunk for firefox, safari, etc.

**Comment by zach-c-d** [comment]
This seems to be fixed in firefox. Still broken in safari. I'm going to close this issue. I think this is ok to just leave to the passage of time as other browsers catch up to chrome's css compatibility.
